title: Digital Public Goods Backlog
# Description will appear in your document head meta (for
# Google search results) and in your feed.xml site description.
description: > # this means to ignore newlines until "baseurl:"
  Digital Public Goods Backlog
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: "dpgalliance" #if your site has a twitter account, enter it here

# Author Settings
author: Digital Public Goods Backlog # add your name
author-img: logo.jpg # add your photo
about-author: Promoting digital public goods to create a more equitable world. # add description
social-twitter: dpgalliance # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: DPGAlliance # add your Github handle
social-linkedin: dpgalliance # add your Linkedin handle
social-email: dev@digitalpublicgoods.net # add your Email address

# Disqus
discus-identifier: # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
